name: 'hdoc: generate documentation for C++ projects'
description: 'Generate beautiful documentation for C++ projects and host it online.'
inputs:
  compile-commands-path:
    description: 'Path to the compile_commands.json file created by your build system.'
    required: true
    default: ''
  hdoc-api-key:
    description: 'The hdoc API key associated with this project.'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.compile-commands-path }}
    - ${{ inputs.hdoc-api-key }}
branding:
  color: 'purple'
  icon: 'book-open'
